image: $BUILD_IMAGE

stages:
  - buildApks
  - runUiTests

before_script:
  - apt-get update -qy
  - apt-get install -y lftp
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

buildApks:
  stage: buildApks
  script:
    - ./gradlew :app:assembleDebug :app:assembleDebugAndroidTest
  artifacts:
    when: on_success
    name: "ui_tests"
    expire_in: 1d
    paths:
      - app/build/outputs

runUiTests:
  stage: runUiTests
  services:
    - name: $EMULATOR_IMAGE
      alias: emulator1
      command: [ "/entrypoint.sh","5554","5555" ]
    - name: $EMULATOR_IMAGE
      alias: emulator2
      command: [ "/entrypoint.sh","5556","5557" ]
  after_script:
    - ./upload_allure_results.sh
  script:
    - ./copy_apks.sh
    - ./wait_for_it.sh -t 300 emulator1:5555
    - ./wait_for_it.sh -t 300 emulator2:5557
    - ./await_devices.sh 2
    - marathon -m Marathonfile
  artifacts:
    when: always
    expire_in: 1d
    paths:
      - build/reports/marathon